import '@/app/assets/styles/globals.css'

import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import { Providers } from './providers'

const openSans = Open_Sans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${openSans.className} antialiased`}>
        <Providers themeProps={{ attribute: 'class', defaultTheme: 'light' }}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
